dependency updates
ELELAB/PDBminer pull request #70
Opened 2023-11-21 15:28 UTC by DegnKristine

fix #69 to update code to newest dependency versions. 
MAINTENANCE PR.

2023-12-04 15:23 UTC, DegnKristine commented
Note, https://biopython.org/docs/latest/api/Bio.Align.Applications.html the alignment command with be removed in the future, they suggest using `import MuscleCommandline` directly.

2024-02-13 07:56 UTC, DegnKristine commented
Tested 13 feb 2024 with biopython 1.83 - this is still viable.

2024-02-16 09:35 UTC, mtiberti requested changes

2024-02-16 09:35 UTC, mtiberti commented on PDBminer
> +        return [], []
maybe you could return `None` instead? It's usually used as a flag value to mean "no results"

2024-02-16 09:35 UTC, mtiberti commented on PDBminer
> +                                                                           list(chain_df.b_factor),
it's usually more robust to use the `pandas` API to turn something into a list, i.e.

```
chain_df.b_factor.to_list()
```

2024-02-16 12:55 UTC, mtiberti approved these changes

2024-02-16 12:55 UTC, merged